"""Add DigitalTwinSnapshot

Revision ID: 7524a45bab07
Revises: ee40b72d0d37
Create Date: 2026-09-19 10:17:06.187166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7524a45bab07'
down_revision: Union[str, Sequence[str], None] = 'ee40b72d0d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digital_twin_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('data_range_start', sa.DateTime(), nullable=False),
    sa.Column('data_range_end', sa.DateTime(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('data_quality', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digital_twin_snapshots')
    # ### end Alembic commands ###
